# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e21b47dae59058821deb7acfb976fe4cc3a599c3779f28e4fee20ba63edc6fcc27ed002f45f2d86cd73f6fd368ea13739d412aac4e74a24e24ec085d3d15a423

test:
  secret_key_base: 2dda15de8b0979c3ab9c30c78651f1077bb61e634e5243c220815aab785f614f1a5bda5af68f89ec8b9618db0278e5c1ae743734216ea717d7d6f17b1e030644

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
